version: '3.1'
networks:
  mynetwork:
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gladysdb
 #   volumes:
  #    - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  gladys:
    image: gladysassistant/gladys
    container_name: gladys
    depends_on:
      - mysql
    networks:
      - mynetwork
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: gladysdb
    #command: "node init.js &"
    ports:
    - '8080:8080'
    - '80:1443'
